# -*- coding: utf-8 -*-
"""nyobain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pg6EH9YTRXc2GMVquWdoNnqd4Rn0awDX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
import streamlit as st

df = pd.read_csv("https://raw.githubusercontent.com/Nasyaagst/Submission/main/all_data.csv")

# Print title
st.title('Simple Dashboard of AQI of Shunyi Area')

# Convert 'year' column to datetime
df['year'] = pd.to_datetime(df['year'])

# Slider widget for selecting time range
st.sidebar.subheader("Select Time Range")
start_date = st.sidebar.date_input("Start Date", pd.to_datetime('2013-03-01'))
end_date = st.sidebar.date_input("End Date", pd.to_datetime('2017-02-28'))

# Filter data based on selected time range
filtered_df = df[(df['year'] >= start_date) & (df['year'] <= end_date)]

# Display filtered data
st.subheader("Filtered Data")
st.write(filtered_df)

# Calculate maximum and minimum values for each pollutant within the selected time range
max_values = filtered_df[['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']].max()
min_values = filtered_df[['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']].min()

# Calculate maximum AQI within the selected time range
max_aqi = filtered_df['AQI'].max()

# Display maximum and minimum pollutant values and maximum AQI
st.subheader("Maximum Pollutant Values and Maximum AQI")
st.write("Maximum Pollutant Values:")
st.write(max_values)
st.write("Minimum Pollutant Values:")
st.write(min_values)
st.write("Maximum AQI:")
st.write(max_aqi)